### PR TITLE
Bump SpeziFirebase and SpeziAccount

### PR DESCRIPTION
**Pull request by Supereg**
# Bump SpeziFirebase and SpeziAccount

## :recycle: Current situation & Problem
This PR upgrades SpeziFirebase and SpeziAccount to fix some issues around associating the current user account on app startup.

## :gear: Release Notes 
* Fixed an issue where the current user account wouldn't be properly associated on initial app startup

## :books: Documentation
--

## :white_check_mark: Testing
--

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — APPROVED** [review]
Thank you for the updates!

**Comment by Supereg** [comment]
I'm observing weird behavior in the CI. The following happens when running the testInApLogon test (locally they pass)
* Getting a notification dialog (that is seemingly automatically dismissed)
* Receiving a `Error Domain=com.firebase.functions Code=5 "NOT FOUND" UserInfo={NSLocalizedDescription=NOT FOUND}` alert for a short second. Seems to be dismissed automatically.
* Lastly, the test taps on the Account button in the toolbar but nothing happens.

Any clue what the first two observations could stem from? Locally I get a `Failed to configured remote notifications for updated device token: Error Domain=com.firebase.functions Code=5 "NOT FOUND" UserInfo={NSLocalizedDescription=NOT FOUND}` message. I assume that's fine, but I have the firebase emulator running with all the functions defined in this repo? Is the firebase setup in this repo still valid?

**Comment by PSchmiedmayer** [comment]
@Supereg I think the firebase setup in this repo is outdated. We plan to address this this week with updating the README and incorporating the real ENGAGE-HF Firebase repo, @nriedman has this on his radar and we could easily add this to this PR to merge them together 👍

**Comment by Supereg** [comment]
Sounds good 👍

**Comment by pauljohanneskraft** [comment]
Closing this since #92 already specifies SpeziFirebase and SpeziAccount versions more recent than specified here - feel free to reopen, if I missed something that this PR includes and is needed for the project beyond just the dependency update.

**Pull request closed without merging**
