### PR TITLE
Fix Notification Registration

### PR DESCRIPTION
**Pull request by PSchmiedmayer**
# Fix Notification Registration

## :recycle: Current situation & Problem
- Firebase is doing method swizzling ... not great and breaks the notification registration.
  - https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in

## :gear: Release Notes 
- Disable method swizzling and fix notifications mechanism.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PSchmiedmayer** [comment]
@pauljohanneskraft @nriedman @Supereg I will create a PR in Spezi to add better diagnostics around this + we should set this flag in the template application. An other reason why swizzling is not a great idea.

**Comment by Supereg** [comment]
What issues were the swizzeled methods causing? 
It seems we can easily add the necessary infrastructure within SpeziFirebase using a [`NotificationTokenHandler`](https://swiftpackageindex.com/stanfordspezi/spezi/1.7.3/documentation/spezi/notificationtokenhandler) that sets the deviceToken in [`Messaging`](https://firebase.google.com/docs/cloud-messaging/ios/client#token-swizzle-disabled).
Another example of a framework trying to do too much magic.

**Comment by PSchmiedmayer** [comment]
@Supereg The delegate methods in the Spezi subclass of the application delegate were never called. Therefore we ran into timeouts even on App Store and TestFlight builds.
Pretty sure this works well in a normal use case but they might not correctly dispatch a call to the actual implementation in a case where you have a subclass hierarchy as we have.

Agree; if someone needs to do this they can pass all these things to Firebase manually and it shouldn't be a blocker in any way or form. And TBH we don't want or should use any of the analytics functionality always so even better that it's not just grabbing data and tokens behind the scenes ...

**Comment by Supereg** [comment]
For context, this seems to be the location where they create the selectors for the delegate methods: https://github.com/google/GoogleUtilities/blob/d6cf51c4617a34bbce94a25428051d1aa98c2e44/GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m#L478-L488.
Might it make sense to report this as an issue to the GoogleUtilities project that their setup fails with certain class inheritances?

Thank you for the documentation changes in Spezi 🚀

**Comment by PSchmiedmayer** [comment]
Agree; we can report this to Google. I have made the unfortunate experience that their support, especially around Firebase, is non-responsive. But maybe creating an issue in the repo might lead to some better results, their engineers & technical team members seem to be responsive & competent.

**Comment by Supereg** [comment]
Just reported it as https://github.com/firebase/firebase-ios-sdk/issues/13566. In my minimal reproducible example I found that it seemingly never calls the original delegate. So it is now even the inheritance we use that is the culprit. It seems this feature is just broken.

**Comment by PSchmiedmayer** [comment]
Thank you @Supereg!

**Pull request merged**
